# Generated by Django 4.2.5 on 2023-10-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0007_auto_20200118_2040"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultation",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="diseaseinfo",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="rating_review",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
